version: "3"
services:
    database:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
        ports:
            -   5778:5432
        volumes:
            - database:/var/lib/postgresql/data
volumes:
    data:
