"""cascade settings

Revision ID: 4587187150d0
Revises: 52e3c41e28b9
Create Date: 2022-04-05 13:19:17.816966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4587187150d0'
down_revision = '52e3c41e28b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
