"""create table water sprinkler

Revision ID: 16720f290532
Revises: 6bc2694eca33
Create Date: 2022-04-05 13:06:33.490042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16720f290532'
down_revision = '6bc2694eca33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('water_sprinklers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime_watering', sa.DateTime(), nullable=False),
    sa.Column('pressure', sa.Integer(), nullable=False),
    sa.Column('water_flow', sa.Integer(), nullable=False),
    sa.Column('opening_time', sa.String(), nullable=False),
    sa.Column('water_sprinklers_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['water_sprinklers_id'], ['water_sprinklers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plants', sa.Column('vase', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'vase')
    op.drop_table('settings')
    op.drop_table('water_sprinklers')
    # ### end Alembic commands ###
