"""update table settings

Revision ID: 01b54aaf7877
Revises: 4587187150d0
Create Date: 2022-04-05 14:41:07.563034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01b54aaf7877'
down_revision = '4587187150d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('settings', sa.Column('hour_watering', sa.Integer(), nullable=False))
    op.add_column('settings', sa.Column('minutes_watering', sa.Integer(), nullable=False))
    op.drop_column('settings', 'datetime_watering')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('datetime_watering', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('settings', 'minutes_watering')
    op.drop_column('settings', 'hour_watering')
    op.drop_column('settings', 'date_start')
    # ### end Alembic commands ###
