"""update is_active table water sprinkler

Revision ID: 992dd3ced435
Revises: ff54c4664247
Create Date: 2022-04-06 06:04:22.254364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992dd3ced435'
down_revision = 'ff54c4664247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('water_sprinklers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_sprinklers', 'is_active')
    # ### end Alembic commands ###
